# Generated by Django 5.2.14 on 2026-06-12 13:13

import bulletin_studio_plugin.services.layout
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0042_productitemtype_valid_for_days'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('language', models.CharField(default='en', help_text='Used to format dates in the generated PDF', max_length=10, verbose_name='Language')),
                ('page_size', models.CharField(default='A4', max_length=10, verbose_name='Page size')),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10, verbose_name='Orientation')),
                ('layout', models.JSONField(default=bulletin_studio_plugin.services.layout.default_layout, verbose_name='Layout')),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin Template',
                'verbose_name_plural': 'Bulletin Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BulletinPublishConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_for_days', models.PositiveIntegerField(default=10, help_text='Fallback validity when the issue has no period end', verbose_name='Valid for (days)')),
                ('issue_title_pattern', models.CharField(default='{product_name} - {period}', max_length=255, verbose_name='Issue title pattern')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.product', verbose_name='Product')),
                ('product_item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.productitemtype', verbose_name='Product Item Type')),
                ('product_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page', verbose_name='Product Page')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.servicecategory', verbose_name='Service Category')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publish_config', to='bulletin_studio_plugin.bulletintemplate')),
            ],
            options={
                'verbose_name': 'Bulletin Publish Config',
            },
        ),
        migrations.CreateModel(
            name='BulletinIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Issue number')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue date')),
                ('period_start', models.DateField(verbose_name='Period start')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Period end')),
                ('layout_snapshot', models.JSONField(verbose_name='Layout snapshot')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Content overrides')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('generated', 'Generated'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bulletin_studio/pdfs/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.customdocumentmodel')),
                ('product_item_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='bulletin_studio_plugin.bulletintemplate')),
            ],
            options={
                'verbose_name': 'Bulletin Issue',
                'verbose_name_plural': 'Bulletin Issues',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='bulletin_studio/assets/')),
                ('params_hash', models.CharField(max_length=64)),
                ('raster_file_id', models.IntegerField(blank=True, null=True)),
                ('raster_time', models.DateTimeField(blank=True, null=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('rendered_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='bulletin_studio_plugin.bulletinissue')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bulletinissue',
            constraint=models.UniqueConstraint(fields=('template', 'period_start'), name='unique_issue_per_period'),
        ),
        migrations.AddConstraint(
            model_name='issueasset',
            constraint=models.UniqueConstraint(fields=('issue', 'element_id'), name='unique_asset_per_element'),
        ),
    ]
